[program:naz-scheduler]
process_name=%(program_name)s
command=php /var/www/autoreply/backend/artisan schedule:work --run --no-interaction
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/autoreply/backend/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=root
environment=APP_ENV="production"
