[program:naz-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/autoreply/backend/artisan queue:work --tries=3 --timeout=300 --sleep=3 --max-jobs=1000
autostart=true
autorestart=true
stopasgroup=true
stopwaitsecs=3600
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/autoreply/backend/storage/logs/queue-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=root
environment=APP_ENV="production"
