[program:naz-scheduler]
process_name=%(program_name)s
command=php /var/www/autoreply/artisan schedule:work --no-interaction
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/www/autoreply/storage/logs/scheduler.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
user=root
environment=APP_ENV="production"
